### ISSUE TITLE
Feature Request: Create a bookmarklet version of the extension

### ISSUE THREAD

**Issue by fredclown** [rnikko/spotify-playback-speed#2]
I love your extension. I use it at home quite a lot. However, it is not possible on my work machine due to corporate policy locking down the ability to install extensions. I'm sure there are others that would be in the same boat. It would be awesome to have a bookmarklet version of this (if it is possible) so that it could be used without having to be installed first.

**Comment by rnikko** [comment]
Updated with bookmarklet version

**Comment by fredclown** [comment]
Works great! Thanks sir.
